//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService {
    using System.Runtime.Serialization;
    using System;
    using ToDo.Infrastructure;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoItem", Namespace="http://schemas.datacontract.org/2004/07/ToDoProxeService")]
    [System.SerializableAttribute()]
    public partial class ToDoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged, IToDoItem {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToDoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCompleted {
            get {
                return this.IsCompletedField;
            }
            set {
                if ((this.IsCompletedField.Equals(value) != true)) {
                    this.IsCompletedField = value;
                    this.RaisePropertyChanged("IsCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToDoId {
            get {
                return this.ToDoIdField;
            }
            set {
                if ((this.ToDoIdField.Equals(value) != true)) {
                    this.ToDoIdField = value;
                    this.RaisePropertyChanged("ToDoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ToDoProxyService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateToDoItem", ReplyAction="http://tempuri.org/IService1/CreateToDoItemResponse")]
        Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem CreateToDoItem(Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateToDoItem", ReplyAction="http://tempuri.org/IService1/CreateToDoItemResponse")]
        System.Threading.Tasks.Task<Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem> CreateToDoItemAsync(Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        int CreateUser(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        System.Threading.Tasks.Task<int> CreateUserAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteToDoItem", ReplyAction="http://tempuri.org/IService1/DeleteToDoItemResponse")]
        void DeleteToDoItem(int todoItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteToDoItem", ReplyAction="http://tempuri.org/IService1/DeleteToDoItemResponse")]
        System.Threading.Tasks.Task DeleteToDoItemAsync(int todoItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTodoList", ReplyAction="http://tempuri.org/IService1/GetTodoListResponse")]
        Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem[] GetTodoList(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTodoList", ReplyAction="http://tempuri.org/IService1/GetTodoListResponse")]
        System.Threading.Tasks.Task<Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem[]> GetTodoListAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateToDoItem", ReplyAction="http://tempuri.org/IService1/UpdateToDoItemResponse")]
        void UpdateToDoItem(Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem todo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateToDoItem", ReplyAction="http://tempuri.org/IService1/UpdateToDoItemResponse")]
        System.Threading.Tasks.Task UpdateToDoItemAsync(Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem todo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.IService1>, Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem CreateToDoItem(Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem item) {
            return base.Channel.CreateToDoItem(item);
        }
        
        public System.Threading.Tasks.Task<Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem> CreateToDoItemAsync(Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem item) {
            return base.Channel.CreateToDoItemAsync(item);
        }
        
        public int CreateUser(string name) {
            return base.Channel.CreateUser(name);
        }
        
        public System.Threading.Tasks.Task<int> CreateUserAsync(string name) {
            return base.Channel.CreateUserAsync(name);
        }
        
        public void DeleteToDoItem(int todoItemId) {
            base.Channel.DeleteToDoItem(todoItemId);
        }
        
        public System.Threading.Tasks.Task DeleteToDoItemAsync(int todoItemId) {
            return base.Channel.DeleteToDoItemAsync(todoItemId);
        }
        
        public Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem[] GetTodoList(int userId) {
            return base.Channel.GetTodoList(userId);
        }
        
        public System.Threading.Tasks.Task<Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem[]> GetTodoListAsync(int userId) {
            return base.Channel.GetTodoListAsync(userId);
        }
        
        public void UpdateToDoItem(Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem todo) {
            base.Channel.UpdateToDoItem(todo);
        }
        
        public System.Threading.Tasks.Task UpdateToDoItemAsync(Karnitsky_Dubodel_DummyToManager.dll.ToDoProxyService.ToDoItem todo) {
            return base.Channel.UpdateToDoItemAsync(todo);
        }
    }
}
